# Generated by Django 4.2.3 on 2023-07-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duvar_kagidi',
            name='kategori',
            field=models.CharField(choices=[('düz', 'düz'), ('damask', 'damask'), ('çizgili', 'çizgili'), ('taş desen', 'taş desen')], default='düz', max_length=100),
        ),
        migrations.AlterField(
            model_name='duvar_kagidi',
            name='title',
            field=models.TextField(),
        ),
    ]
