# Generated by Django 4.2.3 on 2023-07-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0004_alter_portfolio_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='duvar_kagidi',
        ),
    ]
