# Generated by Django 4.2.3 on 2023-07-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0006_duvar_paneli_category_duvar_paneli_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='salon_citasi',
            new_name='Citalama_Dekor',
        ),
    ]
