# Generated by Django 4.2.3 on 2023-07-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0007_rename_salon_citasi_citalama_dekor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duvar_paneli',
            name='category',
        ),
    ]
