# Generated by Django 4.2.3 on 2023-07-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("akademi", "0008_remove_duvar_paneli_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="akadem1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="akadem1/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("duz", "Düz"),
                            ("damask", "Damask"),
                            ("cizgili", "Çizgili"),
                            ("tas_desen", "Taş Desen"),
                            ("cocuk", "Çocuk"),
                            ("cicek_desen", "Çiçek Desen"),
                            ("kircilli", "Kırçıllı"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.CharField(max_length=10)),
                ("title", models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="duvar_kagidi",
            name="category",
            field=models.CharField(
                choices=[
                    ("duz", "Düz"),
                    ("damask", "Damask"),
                    ("cizgili", "Çizgili"),
                    ("tas_desen", "Taş Desen"),
                    ("cocuk", "Çocuk"),
                    ("cicek_desen", "Çiçek Desen"),
                    ("kircilli", "Kırçıllı"),
                ],
                max_length=20,
            ),
        ),
    ]
