# Generated by Django 4.2.3 on 2023-07-26 14:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("akademi", "0013_serisonu_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="serisonu_model",
            name="category",
        ),
    ]
