# Generated by Django 4.2.3 on 2023-07-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("akademi", "0016_akadem4_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="akadem1_model",
            name="category2",
            field=models.CharField(
                choices=[
                    ("akadem1_gold", "Akadem1 Gold"),
                    ("akadem1_for", "Akadem1 For"),
                    ("akadem1_black", "Akadem1 Black"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
