# Generated by Django 4.2.3 on 2023-07-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("akademi", "0018_remove_akadem1_model_category2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="akadem1_model",
            name="category2",
            field=models.CharField(
                choices=[
                    ("gold", "Akadem1 Gold"),
                    ("for", "Akadem1 For"),
                    ("black", "Akadem1 Black"),
                    ("duz", "Düz"),
                    ("damask", "Damask"),
                    ("cizgili", "Çizgili"),
                    ("tas_desen", "Taş Desen"),
                    ("cocuk", "Çocuk"),
                    ("cicek_desen", "Çiçek Desen"),
                    ("kircilli", "Kırçıllı"),
                ],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
