# Generated by Django 4.2.3 on 2023-07-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("akademi", "0020_remove_akadem1_model_category2_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog_photo/")),
                ("description", models.TextField(max_length=10000)),
                ("title", models.CharField(max_length=100)),
            ],
        ),
    ]
