# Generated by Django 4.2.3 on 2023-07-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0023_alter_akadem1_model_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akadem1_model',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='akadem1_model',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
