# Generated by Django 4.2.3 on 2023-08-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0024_alter_akadem1_model_price_alter_akadem1_model_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='poster_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='poster_photo/')),
                ('price', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='akadem1_model',
            name='category',
            field=models.CharField(choices=[('duz', 'Düz'), ('damask', 'Damask'), ('cizgili', 'Çizgili'), ('tas_desen', 'Taş Desen'), ('cocuk', 'Çocuk'), ('cicek_desen', 'Çiçek Desen'), ('kircilli', 'Kırçıllı')], max_length=20),
        ),
        migrations.AlterField(
            model_name='akadem2_model',
            name='category',
            field=models.CharField(choices=[('duz', 'Düz'), ('damask', 'Damask'), ('cizgili', 'Çizgili'), ('tas_desen', 'Taş Desen'), ('cocuk', 'Çocuk'), ('cicek_desen', 'Çiçek Desen'), ('kircilli', 'Kırçıllı')], max_length=20),
        ),
        migrations.AlterField(
            model_name='akadem3_model',
            name='category',
            field=models.CharField(choices=[('duz', 'Düz'), ('damask', 'Damask'), ('cizgili', 'Çizgili'), ('tas_desen', 'Taş Desen'), ('cocuk', 'Çocuk'), ('cicek_desen', 'Çiçek Desen'), ('kircilli', 'Kırçıllı')], max_length=20),
        ),
        migrations.AlterField(
            model_name='akadem4_model',
            name='category',
            field=models.CharField(choices=[('duz', 'Düz'), ('damask', 'Damask'), ('cizgili', 'Çizgili'), ('tas_desen', 'Taş Desen'), ('cocuk', 'Çocuk'), ('cicek_desen', 'Çiçek Desen'), ('kircilli', 'Kırçıllı')], max_length=20),
        ),
    ]
