# Generated by Django 4.2.3 on 2023-08-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0025_poster_model_alter_akadem1_model_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akadem1_model',
            name='category',
            field=models.CharField(choices=[('duz', 'Düz'), ('damask', 'Damask'), ('cizgili', 'Çizgili'), ('tas_desen', 'Taş Desen'), ('cocuk', 'Çocuk'), ('cicek_desen', 'Çiçek Desen'), ('kircilli', 'Kırçıllı'), ('mermer', 'Mermer')], max_length=20),
        ),
    ]
