# Generated by Django 4.2.3 on 2023-08-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0026_alter_akadem1_model_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stropiyer',
            name='category',
        ),
        migrations.AlterField(
            model_name='poster_model',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stropiyer',
            name='image',
            field=models.ImageField(upload_to='stropiyer_photo/'),
        ),
    ]
