# Generated by Django 4.2.3 on 2023-08-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0027_remove_stropiyer_category_alter_poster_model_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='stropiyer',
            new_name='stropiyer_Model',
        ),
    ]
