# Generated by Django 4.2.3 on 2023-08-02 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0028_rename_stropiyer_stropiyer_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stropiyer_model',
            name='price',
        ),
    ]
