# Generated by Django 4.2.3 on 2023-08-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0031_aka_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='stropiyer_model',
            name='category',
            field=models.CharField(choices=[('gobek', 'Göbek')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='duvar_paneli',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
