# Generated by Django 4.2.3 on 2023-08-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0032_stropiyer_model_category_alter_duvar_paneli_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tavan_kaplama',
            name='category',
        ),
    ]
