# Generated by Django 4.2.3 on 2023-08-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0033_remove_tavan_kaplama_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tavan_kaplama',
            name='price',
        ),
        migrations.AlterField(
            model_name='tavan_kaplama',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
