# Generated by Django 4.2.3 on 2023-08-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0034_remove_tavan_kaplama_price_alter_tavan_kaplama_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aka_kids',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='akadem1_model',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='akadem2_model',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='akadem3_model',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='akadem4_model',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='citalama_dekor',
            name='category',
            field=models.CharField(choices=[('salon', 'Salon Çıtası'), ('koridor', 'Koridor Çıtası'), ('yatak', 'Yatak Odası Çıtası')], max_length=20),
        ),
        migrations.AlterField(
            model_name='citalama_dekor',
            name='price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serisonu_model',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
