# Generated by Django 4.2.3 on 2023-08-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0035_alter_aka_kids_price_alter_akadem1_model_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citalama_dekor',
            name='category',
            field=models.CharField(choices=[('cita_ornekleri', 'Çıta Örnekleri'), ('salon', 'Salon Çıtası'), ('koridor', 'Koridor Çıtası'), ('yatak', 'Yatak Odası Çıtası')], max_length=20),
        ),
        migrations.AlterField(
            model_name='citalama_dekor',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
