# Generated by Django 4.2.3 on 2023-08-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0039_remove_citalama_dekor_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='citalama_dekor',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
