# Generated by Django 4.2.3 on 2023-08-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0044_stropiyer_model_price_tavan_kaplama_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akadem1_model',
            name='category',
            field=models.CharField(choices=[('duz', 'Düz'), ('damask', 'Damask'), ('cizgili', 'Çizgili'), ('tas_desen', 'Taş Desen'), ('cocuk', 'Çocuk Odası'), ('cicek_desen', 'Çiçek Desen'), ('kircilli', 'Kırçıllı'), ('mermer', 'Mermer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='akadem3_model',
            name='category',
            field=models.CharField(choices=[('duz', 'Düz'), ('damask', 'Damask'), ('cizgili', 'Çizgili'), ('tas_desen', 'Taş Desen'), ('cocuk', 'Çocuk Odası'), ('cicek_desen', 'Çiçek Desen'), ('kircilli', 'Kırçıllı')], max_length=20),
        ),
        migrations.AlterField(
            model_name='akadem4_model',
            name='category',
            field=models.CharField(choices=[('duz', 'Düz'), ('damask', 'Damask'), ('cizgili', 'Çizgili'), ('tas_desen', 'Taş Desen'), ('cocuk', 'Çocuk Odası'), ('cicek_desen', 'Çiçek Desen'), ('kircilli', 'Kırçıllı')], max_length=20),
        ),
        migrations.AlterField(
            model_name='citalama_dekor',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
