# Generated by Django 4.2.3 on 2023-08-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademi', '0045_alter_akadem1_model_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citalama_dekor',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
